events {
    worker_connections 4096;
}

# TODO potentially think about keepalive config for less delay and performance
# see https://ma.ttias.be/enable-keepalive-connections-in-nginx-upstream-proxy-configurations/

http {
    # Increase map hash bucket size to handle longer domain names
    map_hash_bucket_size 128;

    # Required for WebSocket proxying
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
    # CORS origin mapping for localhost vite development (dev and build/preview as well as actual remote domain)
    map $http_origin $cors_header {
        default "";
        "http://localhost:3000" "$http_origin"; # npm run dev
        "http://localhost:4173" "$http_origin"; # vite preview
        "http://localhost:8080" "$http_origin"; # local dev docker
    }

    # Define the upstream server (your Docker container)
    upstream fastapi_server {
        server 127.0.0.1:8000; # Uvicorn runs on port 8000 inside the container
        keepalive 32; # Keep 32 connections alive for performance
    }

    server {
        listen 5000; # Nginx listens on port 5000 inside the container
        server_name localhost; # Or your domain name

        client_max_body_size 50m; # max body size for client requests

        location / {
            # Add CORS headers only for allowed origins
            add_header 'Access-Control-Allow-Origin' $cors_header always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, Accept' always;
            if ($request_method = 'OPTIONS') {
                return 204;
            }

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 90s; # timeout before nginx throws 504 Gateway Time-out

            proxy_redirect off;
            proxy_buffering off; # Useful for streaming responses

            proxy_pass http://fastapi_server; # Pass requests to the upstream server
        }
    }
}
