[project]
name = "fiscalismia-webscraper"
version = "0.9.2"
requires-python = ">=3.13"
dependencies = [
    "PyJWT[crypto]",
    "fastapi>=0.115.0",
    "uvicorn",
    "uvloop",
    "python-multipart>=0.0.19",
    "tzdata",
    "python-dotenv",
    "playwright",
    "websockets",
    "anthropic[aiohttp]"
]

[tool.ruff]
line-length = 120
target-version = "py313"
indent-width = 2

[tool.ruff.format]
indent-style = "space"
