[supervisord]
nodaemon=true
user=root
logfile=/dev/fd/1
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
loglevel=info

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
# launches service as root so it can access log directories set in nginx.conf
# the nginx.conf then switches the user to unpriviledged nginx once it launches workers
user=root
autostart=true
autorestart=true
startretries=3
priority=1
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
loglevel=info

[program:uvicorn]
command=uvicorn api.main:fastapi --host 0.0.0.0 --timeout-keep-alive 60 --loop uvloop --port 3003
directory=/app
user=python
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
environment=PYTHONUNBUFFERED=1,APP_VERSION="%(ENV_FASTAPI_BUILD_VERSION)s",TMPDIR=/tmp

[group:services]
programs=nginx,uvicorn