### GENERAL CONFIG ###
FASTAPI_GLOBAL_TIMEOUT_SECONDS = 90

### ROUTES ###
BASE_ROUTE = "/fastapi/fiscalismia"
REST_ENDPOINT = "/rest"
WEBSOCKET_ENDPOINT = "/ws"

### BROWSER VIEWPORT ###
BROWSER_VIEWPORT_WIDTH = 1680
BROWSER_VIEWPORT_HEIGHT = 1050

# CDP screencast parameters (used by Page.startScreencast)
CDP_SCREENCAST_FORMAT = "jpeg"
CDP_SCREENCAST_QUALITY = 50
CDP_SCREENCAST_MAX_WIDTH = 1680
CDP_SCREENCAST_MAX_HEIGHT = 1050
CDP_SCREENCAST_EVERY_NTH_FRAME = 1

### STEALTH CONFIG ###
STEALTH_WEBGL_VENDOR = "Intel Inc."
STEALTH_WEBGL_RENDERER = "Intel Iris OpenGL Engine"

### MOUSE MOVEMENT CONFIG ###
MOUSE_BASE_INTERVAL_MS = 10
MOUSE_TIMING_JITTER_SIGMA = 2.5
MOUSE_MIN_INTERVAL_MS = 4
MOUSE_JITTER_SIGMA_PX = 0.5
MOUSE_CONTROL_POINT_SPREAD = 0.15
MOUSE_OVERSHOOT_THRESHOLD_PX = 500
MOUSE_CLICK_HOLD_MIN_MS = 50
MOUSE_CLICK_HOLD_MAX_MS = 150
