### GENERAL CONFIG ###
FASTAPI_GLOBAL_TIMEOUT_SECONDS = 90

### ROUTES ###
BASE_ROUTE = "/fastapi/fiscalismia"
REST_ENDPOINT = "/rest"
WEBSOCKET_ENDPOINT = "/ws"

# CDP screencast parameters (used by Page.startScreencast)
CDP_SCREENCAST_FORMAT = "jpeg"
CDP_SCREENCAST_QUALITY = 50
CDP_SCREENCAST_MAX_WIDTH = 1280
CDP_SCREENCAST_MAX_HEIGHT = 720
CDP_SCREENCAST_EVERY_NTH_FRAME = 1
